version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      nuget-all:
        patterns:
          - "*"
    # Keeps NuGet packages in all projects up-to-date. Scans subfolders under '/'.

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      actions-all:
        patterns:
          - "*"
    # Keeps GitHub Actions workflow versions up-to-date.
